version: "3"
services:
  ranking-service:
    build: .
    restart: always
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - ./:/app
    networks:
      - cf_network
    depends_on:
      - redis_db
      - ranking_db
  redis_db:
    image: redis:6.0
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - cf_network
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - cf_network
  ranking_db:
    image: mysql:8.4.0
    restart: always
    volumes:
      - ranking-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    networks:
      - cf_network
volumes:
  redis-data:
    driver: local
  ranking-db:
  redis-insight:

networks:
  cf_network:
    external: true