version: "3"
services:
  judge-service:
    build: .
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - ./:/app
    networks:
      - cf_network

networks:
  cf_network:
    external: true