# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
  - host: user-service
    name: user-service
    port: 7000
    protocol: http
    routes:
    - name: user-service-route
      paths:
      - /users
      strip_path: true
  - host: contest-service
    name: contest-service
    port: 7700
    protocol: http
    routes:
    - name: contest-service-route
      paths:
      - /contests
      strip_path: true
  - host: submission-service
    name: submission-service
    port: 7770
    protocol: http
    routes:
    - name: submission-service-route
      paths:
      - /submissions
      strip_path: true