version: "3"
services:
 cf_rabbitmq:
    image: "rabbitmq:3.13-management"
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
      - ${MANAGEMENT_PORT}:${CONTAINER_MANAGEMENT_PORT}
    volumes:
      - 'cf_rabbitmq_data:/data'
    networks:
      - cf_network

volumes:
  cf_rabbitmq_data:

networks:
  cf_network:
    external: true